services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_DB: users_db
      POSTGRES_USER: ${DATABASE_USER:-admin}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-admin}
      TZ: 'America/Argentina/Buenos_Aires'
    ports:
      - "5434:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USER:-admin} -d users_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - users-network

  users-service:
    build: .
    restart: always
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "${SERVER_PORT:-8082}:${SERVER_PORT:-8082}"
    env_file:
      - .env
    networks:
      - users-network

networks:
  users-network:
    driver: bridge

volumes:
  pgdata: