version: '3.8'

services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_DB: users
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      TZ: 'America/Argentina'
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d users"]
      interval: 5s
      timeout: 5s
      retries: 5
#
#  java-app:
#    build: .
#    restart: always
#    depends_on:
#      db:
#        condition: service_healthy
#    ports:
#      - "8080:8080"
#      - "5005:5005" # Puerto para la depuraci√≥n remota
#    environment:
#      DATABASE_URL: jdbc:postgresql://db:5432/users
#      DATABASE_USER: admin
#      DATABASE_PASSWORD: admin
#    command: java -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005 -jar /app/app.jar # Comando para ejecutar con el depurador habilitado
#
#volumes:
#  pgdata: